version: "3"
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3307:3306"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=A*123456789*a
      - MYSQL_DATABASE=mysql

  maven-app:
    build: .
    image: bilelbellili/tpachat
    container_name: tpachat
    hostname: tpachat
    tty: true
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local