version: '3.7'
services:
  bored-db:
    container_name: bored-db
    image: mysql:8.0
    networks:
      - bored-network
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tpachato
      - MYSQL_ROOT_PASSWORD=Habib123456789!
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3307:3307"
    restart: always

  bored-app:
    build:
      context: .
    container_name: bored-spring
    image: habeebsoula/tpachat:latest
    ports:
      - "8089:8089"
    networks:
      - bored-network
    depends_on:
      - bored-db
    environment:
      - MYSQL_HOST=bored-db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tpachato
      - MYSQL_PORT=3307

networks:
  bored-network:
    name: bored-network

volumes:
  dbvol:



