version: "3"
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3307:3307"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
      - MYSQL_TCP_PORT: 3307

  maven-app:
    build: .
    image: tpachatlivrableFinal
    container_name: ellou98/tpachatlivrable
    hostname: maven-app
    tty: true
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local