version: "3"
services:

  mysql-service:
    image: mysql:8.0
    networks:
      - maven-mysql-network
    restart: always
    container_name: mysqlv2
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - "3307:3306"
    hostname: mysql
    environment:
      - MYSQL_DATABASE=tpachato
      - MYSQL_ROOT_PASSWORD=A*123456789*a

  maven-app:
    build: .
    image: bilelbellili/tpachat
    container_name: tpachat
    hostname: tpachat
    tty: true
    networks:
      - maven-mysql-network
    depends_on:
      - mysql-service

networks:
  maven-mysql-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local