version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/local/mysql/data
    ports:
      - '3306:3306'
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql

  maven-app:
    build: ellou98/tpachatlivrable
    image: ellou98/tpachatlivrable
    container_name: ellou98/tpachatlivrable
    command: livrable.jar
    hostname: maven-app
    tty: true
    depends_on:
      - mysql

  sonarqube:
    image: sonarqube:8.9.7-community
    ports:
      - '9000:9000'
      - '9092:9092'

  nexus:
    image: sonatype/nexus3
    ports:
      - '8081:8081'

volumes:
  mysql-data:
    driver: local
